version: '3.8'

services:
  # User Service Application (Production)
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-prod
    env_file:
      - .env
    environment:
      NODE_ENV: production
      # Database
      DATABASE_URL: ${DATABASE_URL}
      # Server
      PORT: ${PORT:-3000}
      # Authentication
      JWT_SECRET: ${JWT_SECRET}
      # Email Configuration
      GMAIL_SERVICE: ${GMAIL_SERVICE}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  uploads_data:
